### ISSUE TITLE
Websocket支持

### ISSUE THREAD

**Issue by momocow** [cqmoe/cqhttp-node-sdk#1]
自從Lemoc失效後，伸手黨一臉懵逼地混到了這天，終於發現了cqhttp

首先感謝大老的cqhttp這個插件，先前我使用lemoc與酷Q中間用websocket搭橋
某天酷Q給我報錯說lemoc使用太落後的API，一直找不到替代的插件Orz

不過貌似nodejs這邊的SDK尚未支持websocket?
我匆匆看了一眼源碼，看見用了個kao.js，但實際上我並不了解kao.js裡面支持哪些功能
試用過了一下發現無法連接cqhttp的websocket部分

目前我是用[`websocket`](https://github.com/theturtle32/WebSocket-Node)這個包來實現與cqhttp連接

在這邊給大老表示個支持
如果這個SDK尚未支援websocket的話，在個人程度及時間允許範圍內，我再來提交個PR
\_(:з」∠)\_

**Comment by stdrc** [comment]
谢谢支持哈，欢迎 PR～你可以让 `CQHttp` 类的构造函数接受 `ws_root` 之类的参数，只要不破坏现有接口就好啦，或者也可以单独开一个仓库去维护 websocket 版本的 SDK，然后我给你加到 README 里，你看怎么写起来方便吧。

**Comment by momocow** [comment]
websocket 版本的 SDK 將會在以下這個倉庫進行維護
https://github.com/momocow/node-cq-websocket

另外來個小吐槽，位於這個庫 README 文檔的描述，似乎是貼過來沒有修正 lol
> 封装了 web server 相关的代码，让使用 ~~Python~~ 的开发者能方便地开发插件。

**Comment by stdrc** [comment]
哈哈忘记改了，是从 Python SDK 复制过来的（

感谢支持啦，等你 SDK 写好之后，在这里说一下，我把你的 repo 加上去

**Comment by momocow** [comment]
偷瞄到連結已經悄悄掛上((

來個進度說明，目前處於測試階段
不過SDK的架構大致底定，就先一步把文件寫好了。

**Comment by stdrc** [comment]
嗯了解，谢谢你了～
