### ISSUE TITLE
似乎监听不到别人发送的消息，可以帮忙看看吗

### ISSUE THREAD

**Issue by fishcg** [cqmoe/cqhttp-node-sdk#4]
调用代码：
![image](https://user-images.githubusercontent.com/26989449/56138544-b1595e00-5fc9-11e9-859c-fe7d98722757.png)
插件配置：
![image](https://user-images.githubusercontent.com/26989449/56138568-bf0ee380-5fc9-11e9-8a6a-ed4bea4b7ee5.png)

**Comment by stdrc** [comment]
发一下插件的日志？

**Comment by fishcg** [comment]
请问如何查看插件的日志呢，不过看到酷Q的日志是收到了消息的，抱歉因为刚开始就接触酷Q，不是很了解

**Comment by stdrc** [comment]
在 酷Q 的 `data/app/io.github.richardchien.coolqhttpapi/log/`

fishcg <notifications@github.com>于2019年4月15日 周一23:32写道：

**Comment by fishcg** [comment]
![image](https://user-images.githubusercontent.com/26989449/56226436-c99eab00-60a5-11e9-8a7b-fc96649c1b4f.png)
因为我是在 docker 中运行，所以需要把 `127.0.0.1` 改为宿主机的 IP，感谢指点！

**Comment by fishcg** [comment]
哦 我明白了，以为我是在 docker 中运行，所以需要把 `127.0.0.1` 改为宿主机的 IP，即 `172.17.0.1`
