### ISSUE TITLE
希望事件上报的回调函数支持 promise

### ISSUE THREAD

**Issue by Ice-Hazymoon** [cqmoe/cqhttp-node-sdk#5]
有很多情况下需要用到Promise，希望添加支持

**Comment by stdrc** [comment]
其实我也不太懂 Promise 2333，以后研究一下吧，最近没空维护这个了，如果确实需要的话，可以看看社区里另一个大佬封装的 node sdk
https://github.com/momocow/node-cq-websocket 符不符合你的需求

Ice-Hazymoon <notifications@github.com>于2019年5月27日 周一00:18写道：

**Comment by Ice-Hazymoon** [comment]
感谢回复，期待能增加支持www
