### ISSUE TITLE
为什么服务器机器人apiRoot会报错

### ISSUE THREAD

**Issue by zhaoAAAAA** [cqmoe/cqhttp-node-sdk#6]
![image](https://user-images.githubusercontent.com/53263455/68097194-834d5400-fef0-11e9-8e79-276a2aba2936.png)
(node:31683) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:5700

**Comment by zhaoAAAAA** [comment]
centos

**Comment by zhaoAAAAA** [comment]
(node:31889) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 172.24.12.106:5700
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
(node:31889) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

为什么可以接收消息但不能发送消息呢

**Comment by stdrc** [comment]
先测试下 apiRoot 能不能访问呢？
